class_name Env

static func default():
	var env = {
		"true": true,
		"false": false,
		"v2": Procedure.new(Symbol.new("v2")),
		"v3": Procedure.new(Symbol.new("v3")),
		"set-x!": Procedure.new(Symbol.new("set-x!")),
		"set-y!": Procedure.new(Symbol.new("set-y!")),
		"set-z!": Procedure.new(Symbol.new("set-z!")),
		"=": Procedure.new(Symbol.new("eq")),
		"+": Procedure.new(Symbol.new("add")),
		"-": Procedure.new(Symbol.new("subtract")),
		"*": Procedure.new(Symbol.new("multiply")),
		"/": Procedure.new(Symbol.new("divide")),
		">": Procedure.new(Symbol.new("greater_than")),
		"<": Procedure.new(Symbol.new("less_than")),
		"setp!": Procedure.new(Symbol.new("setp!")),
		"getp": Procedure.new(Symbol.new("getp")),
		"children": Procedure.new(Symbol.new("children")),
		"watch": Procedure.new(Symbol.new("watch")),
		"selected-node": Procedure.new(Symbol.new("selected-node")),
		"selected-nodes": Procedure.new(Symbol.new("selected-nodes")),
		"list-properties": Procedure.new(Symbol.new("list-properties")),
		"count": Procedure.new(Symbol.new("count")),
		"get-node": Procedure.new(Symbol.new("get-node")),
		"find-node": Procedure.new(Symbol.new("find-node")),
		"find-nodes": Procedure.new(Symbol.new("find-nodes")),
		"all-nodes": Procedure.new(Symbol.new("all-nodes")),
		"find-parent": Procedure.new(Symbol.new("find-parent")),
		"connect": Procedure.new(Symbol.new("connect")),
		"parent": Procedure.new(Symbol.new("parent")),
		"list": Procedure.new(Symbol.new("list")),
		"dict": Procedure.new(Symbol.new("dict")),
		"get": Procedure.new(Symbol.new("get")),
		"assoc!": Procedure.new(Symbol.new("assoc!")),
		"dissoc!": Procedure.new(Symbol.new("dissoc!")),
		"merge": Procedure.new(Symbol.new("merge")),
		"int": Procedure.new(Symbol.new("int")),
		"split": Procedure.new(Symbol.new("split")),
		"reverse": Procedure.new(Symbol.new("reverse")),
		"str": Procedure.new(Symbol.new("str")),
		"print": Procedure.new(Symbol.new("print")),
		"log": Procedure.new(Symbol.new("log")),
		"inspect": Procedure.new(Symbol.new("inspect")),
		"do": Procedure.new(Symbol.new("do")),
	}
	
	return env
